// export const options1 = [
//     { value: "wheelAlignment", label: "Wheel Alignment" },
//     { value: "wheelBalancing", label: "Wheel Balancing" },
//     { value: "waterWash", label: "Water Wash" },
//     { value: "wheelCap", label: "Wheel Cap" },
//     { value: "mouth", label: "Mouth" },
//     { value: "bikeWash", label: "Bike Wash" },
// ];

// export const options2 = [
//     { value: "250", label: "250", link: "wheelAlignment" },
//     { value: "300", label: "300", link: "wheelAlignment" },
//     { value: "350", label: "350", link: "wheelAlignment" },
//     { value: "400", label: "400", link: "wheelAlignment" },
//     { value: "450", label: "450", link: "wheelAlignment" },
//     { value: "500", label: "500", link: "wheelAlignment" },
//     { value: "300", label: "300", link: "waterWash" },
//     { value: "350", label: "350", link: "waterWash" },
//     { value: "400", label: "400", link: "waterWash" },
//     { value: "450", label: "450", link: "waterWash" },
//     { value: "500", label: "500", link: "waterWash" },
//     { value: "50", label: "50", link: "mouth" },
//     { value: "100", label: "100", link: "mouth" },
//     { value: "100", label: "100", link: "bikeWash" },
//     { value: "75", label: "75", link: "wheelBalancing" },
//     { value: "100", label: "100", link: "wheelBalancing" },
//     { value: "125", label: "125", link: "wheelBalancing" },
//     { value: "150", label: "150", link: "wheelBalancing" },
//     { value: "175", label: "175", link: "wheelBalancing" },
//     { value: "200", label: "200", link: "wheelBalancing" },
//     { value: "900", label: "900", link: "wheelCap" },
//     { value: "1000", label: "1000", link: "wheelCap" },
//     { value: "1100", label: "1100", link: "wheelCap" },
//     { value: "1200", label: "1200", link: "wheelCap" },
//     { value: "1300", label: "1300", link: "wheelCap" },
//     { value: "1400", label: "1400", link: "wheelCap" },
//     { value: "1500", label: "1500", link: "wheelCap" },
// ];

export const options1 = [
    { value: "Wheel Alignment", label: "Wheel Alignment" },
    { value: "Wheel Balancing", label: "Wheel Balancing" },
    { value: "Water Wash", label: "Water Wash" },
    { value: "Wheel Cap", label: "Wheel Cap" },
    { value: "Mouth", label: "Mouth" },
    { value: "Bike Wash", label: "Bike Wash" },
];

export const options2 = [
    { value: "250", label: "250", link: "Wheel Alignment" },
    { value: "300", label: "300", link: "Wheel Alignment" },
    { value: "350", label: "350", link: "Wheel Alignment" },
    { value: "400", label: "400", link: "Wheel Alignment" },
    { value: "450", label: "450", link: "Wheel Alignment" },
    { value: "500", label: "500", link: "Wheel Alignment" },
    { value: "300", label: "300", link: "Water Wash" },
    { value: "350", label: "350", link: "Water Wash" },
    { value: "400", label: "400", link: "Water Wash" },
    { value: "450", label: "450", link: "Water Wash" },
    { value: "500", label: "500", link: "Water Wash" },
    { value: "50", label: "50", link: "Mouth" },
    { value: "100", label: "100", link: "Mouth" },
    { value: "100", label: "100", link: "Bike Wash" },
    { value: "75", label: "75", link: "Wheel Balancing" },
    { value: "100", label: "100", link: "Wheel Balancing" },
    { value: "125", label: "125", link: "Wheel Balancing" },
    { value: "150", label: "150", link: "Wheel Balancing" },
    { value: "175", label: "175", link: "Wheel Balancing" },
    { value: "200", label: "200", link: "Wheel Balancing" },
    { value: "900", label: "900", link: "Wheel Cap" },
    { value: "1000", label: "1000", link: "Wheel Cap" },
    { value: "1100", label: "1100", link: "Wheel Cap" },
    { value: "1200", label: "1200", link: "Wheel Cap" },
    { value: "1300", label: "1300", link: "Wheel Cap" },
    { value: "1400", label: "1400", link: "Wheel Cap" },
    { value: "1500", label: "1500", link: "Wheel Cap" },
];

export const quantity = [
    { value: "1", label: "1" },
    { value: "2", label: "2" },
    { value: "3", label: "3" },
    { value: "4", label: "4" },
    { value: "5", label: "5" },
];
